apiVersion: v1
kind: Service
metadata:
  name: mavenWeb
  namespace: mavenwebapp
spec:
  type: LoadBalancer
  selector:
    app: mavenWeb
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080